### ISSUE TITLE
[iam_managed_policy] Docs show example with invalid JSON syntax

### ISSUE THREAD

**Issue by mac-chaffee** [ansible-collections/community.aws#175]
##### SUMMARY
The documentation for iam_managed_policy_module has an example ("Update a policy and make it the only version and the default version") which includes a JSON string, but the string has single quotes instead of double quotes.

https://github.com/ansible-collections/community.aws/blob/1d46d10b20958dd86e2ddb5f76bf9ffe087ed3d2/docs/community.aws.iam_managed_policy_module.rst#examples

If you run that example, you will get the following error (pasting to help anyone googling that exact error message)

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1596574923.6952956-198388166755372/AnsiballZ_iam_managed_policy.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1596574923.6952956-198388166755372/AnsiballZ_iam_managed_policy.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1596574923.6952956-198388166755372/AnsiballZ_iam_managed_policy.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.amazon.iam_managed_policy', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_iam_managed_policy_payload_2y472uhd/ansible_iam_managed_policy_payload.zip/ansible/modules/cloud/amazon/iam_managed_policy.py", line 384, in <module>
  File "/tmp/ansible_iam_managed_policy_payload_2y472uhd/ansible_iam_managed_policy_payload.zip/ansible/modules/cloud/amazon/iam_managed_policy.py", line 311, in main
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

The fix is to convert the single quotes to double quotes, and maybe to use the pipe operator like the following:

```yaml
- name: Create IAM Managed Policy
  community.aws.iam_managed_policy:
    policy_name: "PutRetentionPolicy"
    policy_description: "Grants the ability to modify Cloudwatch retention policies"
    policy: |
      {
        "Version": "2012-10-17",
        "Statement":[{
          "Effect": "Allow",
          "Action": "logs:PutRetentionPolicy",
          "Resource": "*"
        }]
      }
    only_version: true
    state: present
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
ommunity.aws.iam_managed_policy_module.rst

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Aug  4 2020, 03:53:03) [GCC 8.3.0]
```

**Comment by tremble** [comment]
Hi @mac-chaffee,

Thanks for you submission, #178 should fix this.  Hopefully we can get this merged before the cut-off for 2.10.
I've also added an example of a nice alternative: because the parameter is of type `json` it's also possible to use YAML / a dictionary and it will be automatically converted into valid JSON.
