### ISSUE TITLE
aws_acm_info fails with KeyError: 'Certificate' when using statuses FAILED

### ISSUE THREAD

**Issue by anthonyxpalermo** [ansible-collections/community.aws#198]
##### SUMMARY
aws_acm_info fails with KeyError: 'Certificate' when using statuses FAILED

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_acm_info

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/palea009/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:28:52) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

MacOS Catalina

##### STEPS TO REPRODUCE

```yaml
- name: obtain ACM certificates
  aws_acm_info:
    aws_access_key: "{{ aws_access_key_info }}"  #
    aws_secret_key: "{{ aws_secret_key_info }}" #
    region:  "{{ aws_region_name_item }}"             # 
    profile:  "{{ acm_account_item.account_name }}" 
    validate_certs: yes
    statuses:  "{{ aws_cert_statuses_item }}"
    debug_botocore_endpoint_logs: yes
  register: acm_certs
  no_log: false
  ignore_errors: false

aws_cert_statuses_item = FAILED

```

##### EXPECTED RESULTS

To not fail 
aws acm list-certificates --certificate-statuses FAILED 
{
    "CertificateSummaryList": [
        {
            "CertificateArn": "arn:aws:acm:us-east-1:xxxxxxxxxxxx:certificate/xxxxxxx-111b-3232-uu44-d555n6s000h4", 
            "DomainName": "personal-domain.onceuponatime.com"
        }
    ]
}
##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/Users/palea009/.ansible/tmp/ansible-tmp-1598132762.090509-98948225592922/AnsiballZ_aws_acm_info.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/palea009/.ansible/tmp/ansible-tmp-1598132762.090509-98948225592922/AnsiballZ_aws_acm_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/palea009/.ansible/tmp/ansible-tmp-1598132762.090509-98948225592922/AnsiballZ_aws_acm_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.amazon.aws_acm_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_aws_acm_info_payload_76Mrni/ansible_aws_acm_info_payload.zip/ansible/modules/cloud/amazon/aws_acm_info.py", line 333, in <module>
  File "/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_aws_acm_info_payload_76Mrni/ansible_aws_acm_info_payload.zip/ansible/modules/cloud/amazon/aws_acm_info.py", line 328, in main
  File "/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_aws_acm_info_payload_76Mrni/ansible_aws_acm_info_payload.zip/ansible/modules/cloud/amazon/aws_acm_info.py", line 291, in get_certificates
  File "/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_aws_acm_info_payload_76Mrni/ansible_aws_acm_info_payload.zip/ansible/module_utils/cloud.py", line 153, in retry_func
KeyError: 'Certificate'
fatal: [prod.certdiscoverytools-wdw.wdprapps.disney.com]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/palea009/.ansible/tmp/ansible-tmp-1598132762.090509-98948225592922/AnsiballZ_aws_acm_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/palea009/.ansible/tmp/ansible-tmp-1598132762.090509-98948225592922/AnsiballZ_aws_acm_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/palea009/.ansible/tmp/ansible-tmp-1598132762.090509-98948225592922/AnsiballZ_aws_acm_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.amazon.aws_acm_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_aws_acm_info_payload_76Mrni/ansible_aws_acm_info_payload.zip/ansible/modules/cloud/amazon/aws_acm_info.py\", line 333, in <module>\n  File \"/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_aws_acm_info_payload_76Mrni/ansible_aws_acm_info_payload.zip/ansible/modules/cloud/amazon/aws_acm_info.py\", line 328, in main\n  File \"/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_aws_acm_info_payload_76Mrni/ansible_aws_acm_info_payload.zip/ansible/modules/cloud/amazon/aws_acm_info.py\", line 291, in get_certificates\n  File \"/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_aws_acm_info_payload_76Mrni/ansible_aws_acm_info_payload.zip/ansible/module_utils/cloud.py\", line 153, in retry_func\nKeyError: 'Certificate'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by anthonyxpalermo** [comment]
To be clear if I download this collection from Galaxy and use it as a collection with Ansible 2.9 it still would not work ?

**Comment by tremble** [comment]
You'll need to download both this collection and the "amazon.aws" collection  (some of the necessary "module_util" code is split across the two repos) but using the collections *should* fix the issue.
