### ISSUE TITLE
community.aws.rds renaming a RDS

### ISSUE THREAD

**Issue by andrewjlowery** [ansible-collections/community.aws#300]
##### SUMMARY

When updating the name of an RDS I am receiving a Error `AttributeError: 'NoneType' object has no attribute 'get_data'` error.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.aws.rds
##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /Users/[username]/github/ce-ansible-dbtooling/ansible.cfg
  configured module search path = ['/Users/[username]/github/ce-ansible-dbtooling/modules']
  ansible python module location = /Users/[username]/local/share/virtualenvs/ce-ansible-dbtooling-T-PezeU5/lib/python3.7/site-packages/ansible
  executable location = /Users/[username]/local/share/virtualenvs/ce-ansible-dbtooling-T-PezeU5/bin/ansible
  python version = 3.7.9 (default, Nov 14 2020, 23:05:21) [Clang 12.0.0 (clang-1200.0.32.27)]

* username redacted
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = memory
DEFAULT_ACTION_PLUGIN_PATH(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = ['/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = ['/Users/[Username]/github/ce-ansible-dbtooling/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = ['/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = ['/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = 5
DEFAULT_GATHERING(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = implicit
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = ['/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_PATH(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = ['/Users/[Username]/github/ce-ansible-dbtooling/modules']
DEFAULT_POLL_INTERVAL(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = 15
DEFAULT_TIMEOUT(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = 10
DEFAULT_TRANSPORT(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = ['/usr/share/ansible_plugins/vars_plugins']
HOST_KEY_CHECKING(/Users/[Username]/github/ce-ansible-dbtooling/ansible.cfg) = False


```

##### OS / ENVIRONMENT

```      
System Version: macOS 10.15.7 (19H2)
Kernel Version: Darwin 19.6.0
```

##### STEPS TO REPRODUCE

```
1. Create a task to update an rds name/identifier
- name: rename the rds
  community.aws.rds:
    apply_immediately: yes
    command: modify
    instance_name: "test-rds"
    new_instance_name: "test-rds-renamed"
    region: eu-west-1
2. Execute the playbook from local
```

##### EXPECTED RESULTS

This should update the RDS and return a a OK status for the task

##### ACTUAL RESULTS

The update is completed in AWS, but it errors with this stack trace 

```paste below
TASK [deployment : rename the rds] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/[Username]/github/ce-ansible-dbtooling/roles/deployment/tasks/main.yml:55
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: [Username]
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir "` echo $HOME/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923 `" && echo ansible-tmp-1605700783.243535-29264-111636051194923="` echo $HOME/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923 `" ) && sleep 0'
Using module file /Users/[Username]/.local/share/virtualenvs/ce-ansible-dbtooling-T-PezeU5/lib/python3.7/site-packages/ansible_collections/community/aws/plugins/modules/rds.py
<127.0.0.1> PUT /Users/[Username]/Dropbox/Mackup/.ansible/tmp/ansible-local-29228u62xk1bk/tmpz81zx9ny TO /Users/[Username]/Dropbox/Mackup/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/AnsiballZ_rds.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/[Username]/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/ /Users/[Username]/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/AnsiballZ_rds.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Users/[Username]/.local/share/virtualenvs/ce-ansible-dbtooling-T-PezeU5/bin/python /Users/[Username]/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/AnsiballZ_rds.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/[Username]/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/[Username]/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/AnsiballZ_rds.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/[Username]/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/AnsiballZ_rds.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/[Username]/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/AnsiballZ_rds.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.aws.plugins.modules.rds', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/4c/sr589631147fhchnl36_xl3wjl70n1/T/ansible_community.aws.rds_payload_zc0mr9gv/ansible_community.aws.rds_payload.zip/ansible_collections/community/aws/plugins/modules/rds.py", line 1396, in <module>
  File "/var/folders/4c/sr589631147fhchnl36_xl3wjl70n1/T/ansible_community.aws.rds_payload_zc0mr9gv/ansible_community.aws.rds_payload.zip/ansible_collections/community/aws/plugins/modules/rds.py", line 1392, in main
  File "/var/folders/4c/sr589631147fhchnl36_xl3wjl70n1/T/ansible_community.aws.rds_payload_zc0mr9gv/ansible_community.aws.rds_payload.zip/ansible_collections/community/aws/plugins/modules/rds.py", line 1123, in modify_db_instance
AttributeError: 'NoneType' object has no attribute 'get_data'
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/[Username]/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/AnsiballZ_rds.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/[Username]/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/AnsiballZ_rds.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/[Username]/.ansible/tmp/ansible-tmp-1605700783.243535-29264-111636051194923/AnsiballZ_rds.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.aws.plugins.modules.rds', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/4c/sr589631147fhchnl36_xl3wjl70n1/T/ansible_community.aws.rds_payload_zc0mr9gv/ansible_community.aws.rds_payload.zip/ansible_collections/community/aws/plugins/modules/rds.py\", line 1396, in <module>\n  File \"/var/folders/4c/sr589631147fhchnl36_xl3wjl70n1/T/ansible_community.aws.rds_payload_zc0mr9gv/ansible_community.aws.rds_payload.zip/ansible_collections/community/aws/plugins/modules/rds.py\", line 1392, in main\n  File \"/var/folders/4c/sr589631147fhchnl36_xl3wjl70n1/T/ansible_community.aws.rds_payload_zc0mr9gv/ansible_community.aws.rds_payload.zip/ansible_collections/community/aws/plugins/modules/rds.py\", line 1123, in modify_db_instance\nAttributeError: 'NoneType' object has no attribute 'get_data'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by andrewjlowery** [comment]
seems if you set wait it works as expected.

```
 if module.params.get('wait'):
        resource = await_resource(conn, result, 'available', module)
    else:
        resource = conn.get_db_instance(instance_name)
```

**Comment by alinabuzachis** [comment]
Thank you for reporting the issue @andrewjlowery. Would you be interested in raising the PR for issue?
