### ISSUE TITLE
aws_ssm windows 2016 connection plugin 

### ISSUE THREAD

**Issue by flavioelawi** [ansible-collections/community.aws#31]
##### SUMMARY
When connecting to a windows instance the output may not be correctly parsed, as the `$LASTEXITCODE` is empty, I still haven't successfully executed a playbook on windows using this connection plugin.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

connection plugin aws_ssm.py

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = None
  configured module search path = ['/Users/flavioel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/flavioel/.virtualenvs/ansible_ssm/lib/python3.6/site-packages/ansible
  executable location = /Users/flavioel/.virtualenvs/ansible_ssm/bin/ansible
  python version = 3.6.10 (default, Jan 27 2020, 23:07:04) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```paste below
empty
```

##### OS / ENVIRONMENT

Source: MacOs 10.14.6 , on Python3.6
Target: `Microsoft Windows Server 2016 Datacenter`
SSM Agent version: `2.3.542.0`

##### STEPS TO REPRODUCE

```yaml
- hosts: aws_ec2
  tasks:
  - name: "Create file"
    ansible.windows.win_file:
      path: C:\Temp\foo.conf
      state: touch
```

##### EXPECTED RESULTS

The playbook executes, and it either returns a success or a failure

##### ACTUAL RESULTS

I have added a `traceback.print_exc()` in the `wrapped` function, to get the visible stack trace.

```paste below
TASK [Gathering Facts] ***************************************************************************************************
task path: /Users/flavioel/workplace/controller/windows_create_file.yml:1
<i-04c99feadf7cc554b> ESTABLISH SSM CONNECTION TO: i-04c99feadf7cc554b
<i-04c99feadf7cc554b> SSM COMMAND: ['/usr/local/bin/session-manager-plugin', '{"SessionId": "SESSION_REDACTED-0bf26d5cdb7b1a368", "TokenValue": "AAEAATKgop2KMV5Pm56w1z1JlmqGKzRnAc5WrJ7aaYCdCLYcAAAAAF6N6Fhu+Dq5kCKxyhapfWIM4rH//TaIqFsTfZJAXfN7nc7JjMD18AoVsmN4ZwlC7nF2OsEG3IKKrFNggtBZyLMYHaP+GsWHwS3sNu9nA73q3vIFVDlVlNIOlWrlHfTPoD58aYyx/tteSKPd4SWd3DJedb
Lb/qBkfSisgwgMtnUQLuuN0Hie4+pmRgAMMkeXaRYncwKiCYTm0+FcB170lEArzu+Lz+WJBf8suRAzl60BIePHB0669zqtanUiNwIO/wEocWcwVAeFnH/GERy+5I54jJgq6yhZ6W2nsRECNlV/jIZ9PhIjMVm+bmRpV+jsO60Zrg41cBITs6poa2/HOHf+BJPyIqpmAEgsVTykDOQS/ajvGQ==", "StreamUrl": "wss://ssmmessages.us-east-1.amazonaws.com/v1/data-channel/SESSION_REDACTED-0bf26d5cdb7b1a368?role=publish_subscribe"
, "ResponseMetadata": {"RequestId": "a6b1b9b9-4eda-4d5a-a7e8-649a9f8033d5", "HTTPStatusCode": 200, "HTTPHeaders": {"x-amzn-requestid": "a6b1b9b9-4eda-4d5a-a7e8-649a9f8033d5", "content-type": "application/x-amz-json-1.1", "content-length": "622", "date": "Wed, 08 Apr 2020 15:06:00 GMT"}, "RetryAttempts": 0}}', 'us-east-1', 'StartSession', '', '{"Targe
t": "i-04c99feadf7cc554b"}', 'https://ssm.us-east-1.amazonaws.com']
<i-04c99feadf7cc554b> SSM CONNECTION ID: SESSION_REDACTED-0bf26d5cdb7b1a368
<i-04c99feadf7cc554b> EXEC PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAkAHQAbQBwAF8AcABhAHQAaAAgAD0AIABbAFMAeQBzAHQAZQBtAC4ARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AEUAeABwAGEAbgBkAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGEAcgBpAGEAYgBsAGUAc
wAoACcAJQBUAEUATQBQACUAJwApAAoAJAB0AG0AcAAgAD0AIABOAGUAdwAtAEkAdABlAG0AIAAtAFQAeQBwAGUAIABEAGkAcgBlAGMAdABvAHIAeQAgAC0AUABhAHQAaAAgACQAdABtAHAAXwBwAGEAdABoACAALQBOAGEAbQBlACAAJwBhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADUAOAA2ADMANQA4ADMANQA5AC4AOAA3ADcANgAxADcALQAxADAANAA4ADcAMwA4ADAAMAAzADIAOAA1ADEANAAnAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAtAEkAbgBwAHUAd
ABPAGIAagBlAGMAdAAgACQAdABtAHAALgBGAHUAbABsAE4AYQBtAGUACgBJAGYAIAAoAC0AbgBvAHQAIAAkAD8AKQAgAHsAIABJAGYAIAAoAEcAZQB0AC0AVgBhAHIAaQBhAGIAbABlACAATABBAFMAVABFAFgASQBUAEMATwBEAEUAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAKQAgAHsAIABlAHgAaQB0ACAAJABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQAgAH0AIABFAGwAcwBlACAAewAgAGUAeABpAHQAI
AAxACAAfQAgAH0A
<i-04c99feadf7cc554b> _wrap_command: 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAkAHQAbQBwAF8AcABhAHQAaAAgAD0AIABbAFMAeQBzAHQAZQBtAC4ARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AEUAeABwAGEAbgBkAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGEAcgBpAG
EAYgBsAGUAcwAoACcAJQBUAEUATQBQACUAJwApAAoAJAB0AG0AcAAgAD0AIABOAGUAdwAtAEkAdABlAG0AIAAtAFQAeQBwAGUAIABEAGkAcgBlAGMAdABvAHIAeQAgAC0AUABhAHQAaAAgACQAdABtAHAAXwBwAGEAdABoACAALQBOAGEAbQBlACAAJwBhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADUAOAA2ADMANQA4ADMANQA5AC4AOAA3ADcANgAxADcALQAxADAANAA4ADcAMwA4ADAAMAAzADIAOAA1ADEANAAnAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAtAE
kAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAdABtAHAALgBGAHUAbABsAE4AYQBtAGUACgBJAGYAIAAoAC0AbgBvAHQAIAAkAD8AKQAgAHsAIABJAGYAIAAoAEcAZQB0AC0AVgBhAHIAaQBhAGIAbABlACAATABBAFMAVABFAFgASQBUAEMATwBEAEUAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAKQAgAHsAIABlAHgAaQB0ACAAJABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQAgAH0AIABFAGwAcwBlACAAewAgAG
UAeABpAHQAIAAxACAAfQAgAH0A; echo dIpRQVkRkzKwiYCldGbnIXIsxo $LASTEXITCODE
echo xKPQoAYIrotmsawsGiYuMptuFX
'
<i-04c99feadf7cc554b> EXEC stdout line:
<i-04c99feadf7cc554b> EXEC stdout line: Starting session with SessionId: SESSION_REDACTED-0bf26d5cdb7b1a368
<i-04c99feadf7cc554b> EXEC remaining: 60
<i-04c99feadf7cc554b> EXEC stdout line: Windows PowerShell
<i-04c99feadf7cc554b> EXEC stdout line: Copyright (C) 2016 Microsoft Corporation. All rights reserved.
<i-04c99feadf7cc554b> EXEC stdout line:
PS C:\Windows\system32> echo xKPQoAYIrotmsawsGiYuMptuFractive -Exec
<i-04c99feadf7cc554b> EXEC stdout line: >> PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAkAHQAbQBwAF8AcABhAHQAaAAgAD0AI
<i-04c99feadf7cc554b> EXEC stdout line: ABbAFMAeQBzAHQAZQBtAC4ARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AEUAeABwAGEAbgBkAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGEAcgBpAGEAYgBsAGUAcwAoACcAJQBUAEUATQBQACUAJwApAAoAJAB0AG0AcAAgAD0AIABOAGUAdwAtAEkAdABlAG0AI
<i-04c99feadf7cc554b> EXEC stdout line: AAtAFQAeQBwAGUAIABEAGkAcgBlAGMAdABvAHIAeQAgAC0AUABhAHQAaAAgACQAdABtAHAAXwBwAGEAdABoACAALQBOAGEAbQBlACAAJwBhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADUAOAA2ADMANQA4ADMANQA5AC4AOAA3ADcANgAxADcALQAxADAANAA4ADcAM
<i-04c99feadf7cc554b> EXEC stdout line: wA4ADAAMAAzADIAOAA1ADEANAAnAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAdABtAHAALgBGAHUAbABsAE4AYQBtAGUACgBJAGYAIAAoAC0AbgBvAHQAIAAkAD8AKQAgAHsAIABJAGYAIAAoAEcAZQB0AC0AV
<i-04c99feadf7cc554b> EXEC stdout line: gBhAHIAaQBhAGIAbABlACAATABBAFMAVABFAFgASQBUAEMATwBEAEUAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAKQAgAHsAIABlAHgAaQB0ACAAJABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQAgAH0AI
<i-04c99feadf7cc554b> EXEC stdout line: ABFAGwAcwBlACAAewAgAGUAeABpAHQAIAAxACAAfQAgAH0A; echo dIpRQVkRkzKwiYCldGbnIXIsxo $PS C:\Windows\system32>
<i-04c99feadf7cc554b> EXEC stdout line: >> echo xKPQoAYIrotmsawsGiYuMptuFX
<i-04c99feadf7cc554b> POST_PROCESS:
Traceback (most recent call last):
  File "/Users/flavioel/.ansible/collections/ansible_collections/community/aws/plugins/connection/aws_ssm.py", line 209, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/Users/flavioel/.ansible/collections/ansible_collections/community/aws/plugins/connection/aws_ssm.py", line 403, in exec_command
    returncode, stdout = self._post_process(stdout, mark_begin)
  File "/Users/flavioel/.ansible/collections/ansible_collections/community/aws/plugins/connection/aws_ssm.py", line 441, in _post_process
    last_exit_code = trailer.splitlines()[1]
IndexError: list index out of range
<i-04c99feadf7cc554b> ssm_retry: attempt: 0, caught exception(list index out of range) from cmd (PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAkAHQAbQBwAF8AcABhAHQAaAAgAD0AIABbAFMAeQBzAHQAZQBtAC4ARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA
6AEUAeABwAGEAbgBkAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGEAcgBpAGEAYgBsAGUAcwAoACcAJQBUAEUATQBQACUAJwApAAoAJAB0AG0AcAAgAD0AIABOAGUAdwAtAEkAdABlAG0AIAAtAFQAeQBwAGUAIABEAGkAcgBlAGMAdABvAHIAeQAgAC0AUABhAHQAaAAgACQAdABtAHAAXwBwAGEAdABoACAALQBOAGEAbQBlACAAJwBhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADUAOAA2ADMANQA4ADMANQA5AC4AOAA3ADcANgAxADcALQAxADAANAA4ADcAMwA4ADAAMAA
zADIAOAA1ADEANAAnAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAdABtAHAALgBGAHUAbABsAE4AYQBtAGUACgBJAGYAIAAoAC0AbgBvAHQAIAAkAD8AKQAgAHsAIABJAGYAIAAoAEcAZQB0AC0AVgBhAHIAaQBhAGIAbABlACAATABBAFMAVABFAFgASQBUAEMATwBEAEUAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAKQAgAHsAIABlAHgAaQB0ACAAJAB
MAEEAUwBUAEUAWABJAFQAQwBPAEQARQAgAH0AIABFAGwAcwBlACAAewAgAGUAeABpAHQAIAAxACAAfQAgAH0A...), pausing for 0 seconds
<i-04c99feadf7cc554b> CLOSING SSM CONNECTION TO: i-04c99feadf7cc554b
^C<i-04c99feadf7cc554b> CLOSING SSM CONNECTION TO: i-04c99feadf7cc554b
 [ERROR]: User interrupted execution
```

**Comment by jillr** [comment]
Ansibullbot is not yet running in the collection repos (it's coming soon) so I'll play the role of ansibullbot here to ping the plugin authors: @psharkey @hanumantharaomvl @gau1991

As we discussed in irc, looks like `Windows_Server-2019-English-Full-Base-2019.11.13` is working so likely Windows version specific.

**Comment by flavioelawi** [comment]
I have to rectify this issue, I have verified that the issue was related to a broken instance, spinning up a new one with the image `Windows_Server-2016-English-Full-Base-2020.04.15 (ami-0d3e6055f3c1699c6)` and it works fine.
