### ISSUE TITLE
aws_ssm connection plugin not work on MacOS on Python 2

### ISSUE THREAD

**Issue by jupeter** [ansible-collections/community.aws#314]
##### SUMMARY

When try to do `win_ping` task, receive stack trace exception

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.aws - 1.2.1

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /Users/plpi8001/workspace/ansible-hosts-maintanance/ansible.cfg
  configured module search path = [u'/Users/plpi8001/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/plpi8001/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Jun  5 2020, 22:59:21) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-

```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/Users/plpi8001/workspace/ansible-hosts-maintanance/ansible.cfg) = ['/Users/plpi8001/workspace/ansible-hosts-maintanance/collections']
GALAXY_SERVER_LIST(/Users/plpi8001/workspace/ansible-hosts-maintanance/ansible.cfg) = ['release_galaxy']
INVENTORY_ENABLED(/Users/plpi8001/workspace/ansible-hosts-maintanance/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml']

```

##### OS / ENVIRONMENT
ProductName:        Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H15

##### STEPS TO REPRODUCE

Command: 
> python /usr/local/bin/ansible -m win_ping aws_ec2_platform_windows -vvv

##### EXPECTED RESULTS

OK

##### ACTUAL RESULTS
```
<i-014972904584f6175> CLOSING SSM CONNECTION TO: i-014972904584f6175
The full traceback is:
Traceback (most recent call last):
  File "/Users/plpi8001/Library/Python/2.7/lib/python/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/Users/plpi8001/Library/Python/2.7/lib/python/site-packages/ansible/executor/task_executor.py", line 663, in _execute
    result = self._handler.run(task_vars=variables)
  File "/Users/plpi8001/Library/Python/2.7/lib/python/site-packages/ansible/plugins/action/gather_facts.py", line 86, in run
    res = self._execute_module(module_name=fact_module, module_args=mod_args, task_vars=task_vars, wrap_async=False)
  File "/Users/plpi8001/Library/Python/2.7/lib/python/site-packages/ansible/plugins/action/__init__.py", line 826, in _execute_module
    self._make_tmp_path()
  File "/Users/plpi8001/Library/Python/2.7/lib/python/site-packages/ansible/plugins/action/__init__.py", line 393, in _make_tmp_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "/Users/plpi8001/Library/Python/2.7/lib/python/site-packages/ansible/plugins/action/__init__.py", line 1121, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/Users/plpi8001/workspace/ansible-hosts-maintanance/collections/ansible_collections/community/aws/plugins/connection/aws_ssm.py", line 212, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/Users/plpi8001/workspace/ansible-hosts-maintanance/collections/ansible_collections/community/aws/plugins/connection/aws_ssm.py", line 351, in exec_command
    super(Connection, self).exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/Users/plpi8001/Library/Python/2.7/lib/python/site-packages/ansible/plugins/connection/__init__.py", line 34, in wrapped
    self._connect()
  File "/Users/plpi8001/workspace/ansible-hosts-maintanance/collections/ansible_collections/community/aws/plugins/connection/aws_ssm.py", line 286, in _connect
    self.start_session()
  File "/Users/plpi8001/workspace/ansible-hosts-maintanance/collections/ansible_collections/community/aws/plugins/connection/aws_ssm.py", line 337, in start_session
    self._poll_stdout = select.poll()
AttributeError: 'module' object has no attribute 'poll'
fatal: [i-014972904584f6175]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}

```

**Comment by jupeter** [comment]
https://stackoverflow.com/questions/19740471/cannot-use-python-select-poll-in-mac-os

**Comment by tremble** [comment]
Support for Python 2.x and Python < 3.6 has been dropped by this collection, as such I'm going to close out this issue.
