### ISSUE TITLE
rds_instance state absent  and terminated does nothing

### ISSUE THREAD

**Issue by dhughesbc** [ansible-collections/community.aws#810]
### Summary

When I try to delete an RDS instance via a playbook, the playbook indicates that the operations succeed, but in fact the RDS instance is not removed.

### Issue Type

Bug Report

### Component Name

rds_instance

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/home/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/me/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/me/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/me/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
ERROR! Unexpected Exception, this is probably a bug: No module named 'resolvelib'
the full traceback was:

Traceback (most recent call last):
  File "/home/me/.local/bin/ansible-galaxy", line 104, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/home/me/.local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 26, in <module>
    from ansible.galaxy.collection import (
  File "/home/me/.local/lib/python3.8/site-packages/ansible/galaxy/collection/__init__.py", line 100, in <module>
    from ansible.galaxy.collection.concrete_artifact_manager import (
  File "/home/me/.local/lib/python3.8/site-packages/ansible/galaxy/collection/concrete_artifact_manager.py", line 38, in <module>
    from ansible.galaxy.dependency_resolution.dataclasses import _GALAXY_YAML
  File "/home/me/.local/lib/python3.8/site-packages/ansible/galaxy/dependency_resolution/__init__.py", line 26, in <module>
    from ansible.galaxy.dependency_resolution.providers import CollectionDependencyProvider
  File "/home/me/.local/lib/python3.8/site-packages/ansible/galaxy/dependency_resolution/providers.py", line 33, in <module>
    from resolvelib import AbstractProvider
ModuleNotFoundError: No module named 'resolvelib'

```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /home/me/.local/lib/python3.8/site-packages
Requires: 
Required-by: 
---
Name: boto3
Version: 1.19.3
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /home/me/.local/lib/python3.8/site-packages
Requires: jmespath, botocore, s3transfer
Required-by: 
---
Name: botocore
Version: 1.22.3
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /home/me/.local/lib/python3.8/site-packages
Requires: jmespath, urllib3, python-dateutil
Required-by: s3transfer, boto3

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
<no output>
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)

# db_instance_name variable is a valid identifier
    - name: Find Primary Mysql
      rds_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        db_instance_identifier: "{{ db_instance_name }}"
        region: "{{ region }}"
        tags:
          Name: "{{ db_instance_name }}"
      register: primary_rds

    - name: Remove Primary Mysql
      rds_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        id: "{{ primary_rds.dbi_resource_id }}"
        state: absent
        skip_final_snapshot: True

    - name: Remove Primary Mysql Again
      rds_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        id: "{{ primary_rds.db_instance_identifier }}"
        state: absent
        skip_final_snapshot: True

```

### Expected Results

I expected that the RDS instance would be deleted

### Actual Results

```console (paste below)
TASK [Find Primary Mysql] *****************************************************************
ok: [localhost]

TASK [Remove Primary Mysql] ***************************************************************
ok: [localhost]

TASK [Remove Primary Mysql Again] *********************************************************
ok: [localhost]
```
But the RDS instance is not actually deleted. It still shows as Available in the web console

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by alinabuzachis** [comment]
Hi @dhughesbc, thanks for raising this issue. I noticed that you used `dbi_resource_id` in the first task that attempts to remove the RDS instance. If my understanding is correct, you cannot use `dbi_resource_id` as the identifier of the db instance to be removed, but must instead use the `db_instance_identifier` (as you used in the second task attempting removal, https://docs.aws.amazon.com/cli/latest/reference/rds/delete-db-instance.html).
With `dbi_resource_id`, nothing happens, but when you use `db_instance_identifier`, the DB instance is correctly removed. Idempotency also works as expected.
Let me know please if this clarifies.

**Comment by dhughesbc** [comment]
@alinabuzachis Thanks for your reply. As you saw, I tried using both `dbi_resource_id` and `db_instance_identifier`. Neither one worked for me. If `db_instance_identifier` is the correct identifier, then shouldn't the instance have been removed after the `Remove Primary Mysql Again` task?

**Comment by alinabuzachis** [comment]
@dhughesbc yes, it should be in this way. The only thing coming in mind now is the region. You specified it in the first task and not in the following ones. Could you please check if you are using the correct region for the RDS instance to be deleted?

**Comment by dhughesbc** [comment]
@alinabuzachis Thank you! Adding region fixed the issue. I am a little surprised the task did not error if a required parameter was missing. In any event thanks again for your responses.

**Comment by tremble** [comment]
@dhughesbc,

The parameter isn't "required", because the SDK we use generally picks up a default value (often from ~/.aws or a hard-coded default of "us-east-1").  "nothing" then happened because the instance wasn't found in the region it was using.
